Repository eclipse/antenna, pull requests merged in 2019-08, with the labels that each got.

#229 test(azure): test execution as integration test and add caching
  .ci-scripts/runCLI.sh
  .ci-scripts/test-ExampleTestProject-with-CLI.sh
  .ci-scripts/test-ExampleTestProject-with-gradle.sh
  .ci-scripts/test-ExampleTestProject-with-maven.sh
  .ci-scripts/test-antenna-documentation-site-tests.sh
  .ci-scripts/test-for-licenseHeaders.sh
  .ci-scripts/test-p2-end2end.sh
  .ci-scripts/test-sw360-integration-test.sh
  .travis.yml
  azure-pipelines.yml
  run_all_tests.sh
Labels: waiting for CI

#242 modules(ort): Remove the single package test
  modules/ort/src/test/java/org/eclipse/sw360/antenna/ort/workflow/analyzers/OrtResultAnalyzerTest.java
  modules/ort/src/test/resources/single_package.yml
Labels: waiting for CI

#246 fix: bump version of jackson-databind as suggested by GitHub alerts
  pom.xml
Labels: waiting for CI

#248 modules(ort): Fix the expected scan result test data
  modules/ort/src/test/resources/scan-result.yml
Labels: waiting for CI

#249 core(model): Make the coordinates builder API fluent
  core/model/src/main/java/org/eclipse/sw360/antenna/model/artifact/facts/dotnet/DotNetCoordinates.java
  core/model/src/main/java/org/eclipse/sw360/antenna/model/artifact/facts/java/MavenCoordinates.java
  core/model/src/main/java/org/eclipse/sw360/antenna/model/artifact/facts/javaScript/JavaScriptCoordinates.java
Labels: waiting for CI

#257 fix(test): add missing file to PR #254
  modules/sw360/src/integrationtest/resources/postgres/.gitignore
Labels: minor

#258 AntennaGradlePluginTest: Specify a charset for writeStringToFile()
  assembly/gradle-plugin/src/test/java/org/eclipse/sw360/antenna/frontend/gradle/AntennaGradlePluginTest.java
Labels: waiting for CI

#243 Fix and update Jenkins
  .ci-scripts/Vagrantfile
  .ci-scripts/test-ExampleTestProject-with-gradle.sh
  .ci-scripts/test-ExampleTestProject-with-maven.sh
  .ci-scripts/test-antenna-documentation-site-tests.sh
  Jenkinsfile
  Jenkinsfile.eclipse
  modules/p2/cleanupDependenciesForP2.sh
  run_all_tests.sh
Labels: infrastructure

#262 Fix antenna rest and allow to upload attachments to SW360
  core/model/src/main/java/org/eclipse/sw360/antenna/api/workflow/ConfigurableWorkflowItem.java
  core/runtime/src/main/java/org/eclipse/sw360/antenna/util/ProxySettings.java
  example-projects/mvn-test-project/pom.xml
  modules/sw360/src/main/java/org/eclipse/sw360/antenna/sw360/SW360MetaDataReceiver.java
  modules/sw360/src/main/java/org/eclipse/sw360/antenna/sw360/SW360MetaDataUpdater.java
  modules/sw360/src/main/java/org/eclipse/sw360/antenna/sw360/adapter/SW360ComponentClientAdapter.java
  modules/sw360/src/main/java/org/eclipse/sw360/antenna/sw360/adapter/SW360LicenseClientAdapter.java
  modules/sw360/src/main/java/org/eclipse/sw360/antenna/sw360/adapter/SW360ProjectClientAdapter.java
  modules/sw360/src/main/java/org/eclipse/sw360/antenna/sw360/adapter/SW360ReleaseClientAdapter.java
  modules/sw360/src/main/java/org/eclipse/sw360/antenna/sw360/adapter/SW360UserClientAdapter.java
  modules/sw360/src/main/java/org/eclipse/sw360/antenna/sw360/rest/SW360AttachmentAwareClient.java
  modules/sw360/src/main/java/org/eclipse/sw360/antenna/sw360/rest/SW360AuthenticationClient.java
  modules/sw360/src/main/java/org/eclipse/sw360/antenna/sw360/rest/SW360Client.java
  modules/sw360/src/main/java/org/eclipse/sw360/antenna/sw360/rest/SW360ComponentClient.java
  modules/sw360/src/main/java/org/eclipse/sw360/antenna/sw360/rest/SW360LicenseClient.java
  modules/sw360/src/main/java/org/eclipse/sw360/antenna/sw360/rest/SW360ProjectClient.java
  modules/sw360/src/main/java/org/eclipse/sw360/antenna/sw360/rest/SW360ReleaseClient.java
  modules/sw360/src/main/java/org/eclipse/sw360/antenna/sw360/rest/SW360UserClient.java
  modules/sw360/src/main/java/org/eclipse/sw360/antenna/sw360/rest/resource/SW360Attributes.java
  modules/sw360/src/main/java/org/eclipse/sw360/antenna/sw360/rest/resource/attachments/SW360Attachment.java
  modules/sw360/src/main/java/org/eclipse/sw360/antenna/sw360/rest/resource/releases/SW360Release.java
  modules/sw360/src/main/java/org/eclipse/sw360/antenna/sw360/utils/RestUtils.java
  modules/sw360/src/main/java/org/eclipse/sw360/antenna/sw360/utils/SW360ComponentAdapterUtils.java
  modules/sw360/src/main/java/org/eclipse/sw360/antenna/sw360/utils/SW360ProjectAdapterUtils.java
  modules/sw360/src/main/java/org/eclipse/sw360/antenna/sw360/utils/SW360ReleaseAdapterUtils.java
  modules/sw360/src/main/java/org/eclipse/sw360/antenna/sw360/workflow/SW360ConnectionConfiguration.java
  modules/sw360/src/main/java/org/eclipse/sw360/antenna/sw360/workflow/generators/SW360Updater.java
  modules/sw360/src/main/java/org/eclipse/sw360/antenna/sw360/workflow/processors/SW360Enricher.java
  modules/sw360/src/test/java/org/eclipse/sw360/antenna/sw360/rest/SW360ProjectClientTest.java
Labels: waiting for CI

#268 test(azure): add static code analysis to azure
  azure-pipelines.yml
Labels: waiting for CI
